### ISSUE TITLE
EPIC: import Powertakers & Contracts

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#116]
Icludes: 

- [ ] #25 import and see all the powertakers
- [ ] #51 information PT details
- [ ] #113 Powertaker bank accounts
- [ ] #115 import PT contracts
