### ISSUE TITLE
EPIC: import technical system of all groups 

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#70]
**DoD**

- [ ] #47 register details 1
- [ ] #58 register details 2
- [ ] #29 data sources for registers
- [ ] #64 technical details for registers
- [ ] #66 register readings
- [ ] #48 meter details
- [ ] #61 data source for meter

**Comment by evaklopp** [comment]
not clear: 
#48 how we deal with the manufacturer name and description.
