### ISSUE TITLE
EPIC: Display View

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#91]
Includes:

- [ ] #69 enable display view
- [ ] #77 vivid bubbles (boosting)
- [ ] #87 total daily energy
- [ ] #86 total power consumption
- [ ] #85 arcs for power production
- [ ] #83 power sources
- [ ] #74 show charts
- [ ] #80 show group owner
- [ ] #88 show autarchy
- [ ] #89 display view in browsers an tablets
- [ ] #81 display view on Samsung TV
- [ ] #72 highlight common power consumption (Allgemeinstrom)
